package com.example.moodjournal.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * A single assessment question generated by LLM.
 */
@Data
@NoArgsConstructor
public class AssessmentQuestion {
    private Integer id;
    private String question;
    private String scale;

    public AssessmentQuestion(Integer id, String question, String scale) {
        this.id = id;
        this.question = question;
        this.scale = scale;
    }
}
