package com.example.moodjournal.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * A single assessment question generated by LLM.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class AssessmentQuestion {
    private Integer id;
    private String question;
}
